### ISSUE TITLE
hallo,

### ISSUE THREAD

**Issue by sroesslhuemer** [blinzelaffe/roseguarden#10]

**Comment by sroesslhuemer** [comment]
hallo, ich bekomme immer no rfid tag detected , welche moeglichkeiten habe ich dahinterzukommen verkabelung ist lt. schema

**Comment by mdrobisch** [comment]
Hallo Siegi,
ich hatte dir am 9.11 geschrieben. Ist die Mail evt. im Spam gelandet?

SG
Marcus

**Comment by pakohan** [comment]
I'm a little frustrated since this issue is mentioned twice and the answer is always send via mail. Isn't there a possibility to let everyone see it? :-)
