### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by baskettal** [blinzelaffe/roseguarden#12]
Hallo,

haben Sie vor, in der nächsten Zeit, das Paymentmodul zu implementieren, wie auf Ihrer Weseite beschrieben?

Beste Grüße!

**Comment by mdrobisch** [comment]
Sorry für die späte Antwort.
Nach langer Inaktivität arbeiten wir nun an einem kompletten Remake von Roseguarden.
Wir hoffen hier auch ein Payment-Feature zur Verfügung zu stellen.
Den aktuellen Stand der arbeit ist unter https://gitlab.com/roseguarden/roseguarden zu finden.
